// <auto-generated />
using System;
using Kuva.Notifications.Repository.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kuva.Notifications.EFMigrations.Migrations
{
    [DbContext(typeof(NotificationsDbContext))]
    [Migration("20260509223256_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Kuva.Notifications.Entities.Entities.NotificationAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("NotificationRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StorageReference")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("NotificationRequestId")
                        .HasDatabaseName("IX_NotificationAttachments_NotificationRequestId");

                    b.ToTable("NotificationAttachments", (string)null);
                });

            modelBuilder.Entity("Kuva.Notifications.Entities.Entities.NotificationEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("EventType")
                        .HasColumnType("int");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("NotificationRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("IX_NotificationEvents_CreatedAtUtc");

                    b.HasIndex("EventType")
                        .HasDatabaseName("IX_NotificationEvents_EventType");

                    b.HasIndex("NotificationRequestId")
                        .HasDatabaseName("IX_NotificationEvents_NotificationRequestId");

                    b.ToTable("NotificationEvents", (string)null);
                });

            modelBuilder.Entity("Kuva.Notifications.Entities.Entities.NotificationProvider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConfigurationKey")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("ProviderType")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_NotificationProviders_IsActive");

                    b.HasIndex("Priority")
                        .HasDatabaseName("IX_NotificationProviders_Priority");

                    b.HasIndex("Type")
                        .HasDatabaseName("IX_NotificationProviders_Type");

                    b.ToTable("NotificationProviders", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("7a40f1f4-5e62-4427-90c0-b89ac3cd0001"),
                            ConfigurationKey = "Fake",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Fake Local Provider",
                            Priority = 1,
                            ProviderType = 3,
                            Type = 1
                        });
                });

            modelBuilder.Entity("Kuva.Notifications.Entities.Entities.NotificationRecipient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid>("NotificationRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("Address")
                        .HasDatabaseName("IX_NotificationRecipients_Address");

                    b.HasIndex("NotificationRequestId")
                        .HasDatabaseName("IX_NotificationRecipients_NotificationRequestId");

                    b.ToTable("NotificationRecipients", (string)null);
                });

            modelBuilder.Entity("Kuva.Notifications.Entities.Entities.NotificationRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ExternalReference")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SentAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Source")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("SubjectRendered")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("TemplateCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("TemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("VariablesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("IX_NotificationRequests_CreatedAtUtc");

                    b.HasIndex("ExternalReference")
                        .HasDatabaseName("IX_NotificationRequests_ExternalReference");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_NotificationRequests_Status");

                    b.HasIndex("TemplateCode")
                        .HasDatabaseName("IX_NotificationRequests_TemplateCode");

                    b.HasIndex("TemplateId");

                    b.HasIndex("Type")
                        .HasDatabaseName("IX_NotificationRequests_Type");

                    b.HasIndex("Type", "TemplateId", "ExternalReference")
                        .HasDatabaseName("IX_NotificationRequests_Type_TemplateId_ExternalReference");

                    b.ToTable("NotificationRequests", (string)null);
                });

            modelBuilder.Entity("Kuva.Notifications.Entities.Entities.NotificationSendAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("int");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("FinishedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("NotificationProviderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("NotificationRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProviderMessageId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Success")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("NotificationProviderId");

                    b.HasIndex("NotificationRequestId")
                        .HasDatabaseName("IX_NotificationSendAttempts_NotificationRequestId");

                    b.HasIndex("StartedAtUtc")
                        .HasDatabaseName("IX_NotificationSendAttempts_StartedAtUtc");

                    b.HasIndex("Success")
                        .HasDatabaseName("IX_NotificationSendAttempts_Success");

                    b.ToTable("NotificationSendAttempts", (string)null);
                });

            modelBuilder.Entity("Kuva.Notifications.Entities.Entities.NotificationTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("HtmlBodyTemplate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("RequiredVariablesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubjectTemplate")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("TextBodyTemplate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .HasDatabaseName("IX_NotificationTemplates_Code");

                    b.HasIndex("Type")
                        .HasDatabaseName("IX_NotificationTemplates_Type");

                    b.HasIndex("Type", "Code", "IsActive")
                        .HasDatabaseName("IX_NotificationTemplates_Type_Code_IsActive");

                    b.HasIndex("Type", "Code", "Version")
                        .IsUnique();

                    b.ToTable("NotificationTemplates", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("7a40f1f4-5e62-4427-90c0-b89ac3cd0002"),
                            Code = "ORDER_RECEIVED",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HtmlBodyTemplate = "<h1>Ola, {{customerName}}</h1><p>Seu pedido {{orderNumber}} foi recebido pela loja {{storeName}}.</p>",
                            IsActive = true,
                            Language = "pt-BR",
                            Name = "Pedido recebido",
                            RequiredVariablesJson = "[\"customerName\",\"orderNumber\",\"storeName\"]",
                            SubjectTemplate = "Pedido {{orderNumber}} recebido pela loja",
                            Type = 1,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("7a40f1f4-5e62-4427-90c0-b89ac3cd0003"),
                            Code = "ORDER_READY_FOR_PICKUP",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HtmlBodyTemplate = "<h1>Ola, {{customerName}}</h1><p>Seu pedido esta pronto para retirada na loja {{storeName}}.</p>",
                            IsActive = true,
                            Language = "pt-BR",
                            Name = "Pedido pronto para retirada",
                            RequiredVariablesJson = "[\"customerName\",\"orderNumber\",\"storeName\"]",
                            SubjectTemplate = "Seu pedido {{orderNumber}} esta pronto para retirada",
                            Type = 1,
                            Version = 1
                        });
                });

            modelBuilder.Entity("Kuva.Notifications.Entities.Entities.NotificationAttachment", b =>
                {
                    b.HasOne("Kuva.Notifications.Entities.Entities.NotificationRequest", "NotificationRequest")
                        .WithMany("Attachments")
                        .HasForeignKey("NotificationRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NotificationRequest");
                });

            modelBuilder.Entity("Kuva.Notifications.Entities.Entities.NotificationEvent", b =>
                {
                    b.HasOne("Kuva.Notifications.Entities.Entities.NotificationRequest", "NotificationRequest")
                        .WithMany("Events")
                        .HasForeignKey("NotificationRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NotificationRequest");
                });

            modelBuilder.Entity("Kuva.Notifications.Entities.Entities.NotificationRecipient", b =>
                {
                    b.HasOne("Kuva.Notifications.Entities.Entities.NotificationRequest", "NotificationRequest")
                        .WithMany("Recipients")
                        .HasForeignKey("NotificationRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NotificationRequest");
                });

            modelBuilder.Entity("Kuva.Notifications.Entities.Entities.NotificationRequest", b =>
                {
                    b.HasOne("Kuva.Notifications.Entities.Entities.NotificationTemplate", "Template")
                        .WithMany("Requests")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Template");
                });

            modelBuilder.Entity("Kuva.Notifications.Entities.Entities.NotificationSendAttempt", b =>
                {
                    b.HasOne("Kuva.Notifications.Entities.Entities.NotificationProvider", "NotificationProvider")
                        .WithMany("Attempts")
                        .HasForeignKey("NotificationProviderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Kuva.Notifications.Entities.Entities.NotificationRequest", "NotificationRequest")
                        .WithMany("Attempts")
                        .HasForeignKey("NotificationRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NotificationProvider");

                    b.Navigation("NotificationRequest");
                });

            modelBuilder.Entity("Kuva.Notifications.Entities.Entities.NotificationProvider", b =>
                {
                    b.Navigation("Attempts");
                });

            modelBuilder.Entity("Kuva.Notifications.Entities.Entities.NotificationRequest", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Attempts");

                    b.Navigation("Events");

                    b.Navigation("Recipients");
                });

            modelBuilder.Entity("Kuva.Notifications.Entities.Entities.NotificationTemplate", b =>
                {
                    b.Navigation("Requests");
                });
#pragma warning restore 612, 618
        }
    }
}
