name: Deploy to Azure Container Registry

on:
  push:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  quality-gate:
    uses: Kuva-app/kuva-ci/.github/workflows/quality-gate-pr-dotnet.yml@901c713cfa2a608170de64cd76aa0df3d2f63863
    with:
      DOTNET_VERSION: 10.0.x
      SOLUTION_PATH: Source/Kuva.Notifications.sln
      SOLUTION_KEY: Kuva-app_backend-notifications
    secrets: inherit

  deploy:
    uses: Kuva-app/kuva-ci/.github/workflows/deploy-default-dotnet.yml@901c713cfa2a608170de64cd76aa0df3d2f63863
    needs: quality-gate
    permissions:
      id-token: write
      contents: read
    with:
      DOCKERFILE_PATH: ./Dockerfile
      IMAGE_NAME: kuva-notifications-service
      ACR_NAME: kuvaapp
      ACR_LOGIN_SERVER: kuvaapp.azurecr.io
    secrets: inherit